# Generated by Django 6.0.8 on 2026-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapserver',
            name='birthday_format',
            field=models.CharField(blank=True, help_text='Например MM.dd.yyyy или dd.MM.yyyy. Пусто - порядок по умолчанию.', max_length=32, verbose_name='Формат даты рождения'),
        ),
    ]
