# Generated by Django 6.0.8 on 2026-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_ldapserver_birthday_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивировано')),
                ('login', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Логин')),
                ('password_hash', models.CharField(blank=True, editable=False, max_length=256, verbose_name='Пароль (хеш)')),
                ('description', models.CharField(blank=True, help_text='Какое приложение ходит под этим логином и кто владелец.', max_length=255, verbose_name='Назначение')),
                ('permissions', models.JSONField(blank=True, default=list, help_text='Методы старого API, доступные этому клиенту.', verbose_name='Разрешённые методы')),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последний запрос')),
            ],
            options={
                'verbose_name': 'Клиент API',
                'verbose_name_plural': 'Клиенты API',
                'ordering': ('login',),
            },
        ),
    ]
