# Generated by Django 6.0.8 on 2026-09-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_apiclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_dir',
            field=models.CharField(blank=True, help_text='Организация и UID из 1С внутри хранилища фотографий.', max_length=255, verbose_name='Папка с фото'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='Отпечаток фото'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фото обновлено'),
        ),
    ]
